# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: common.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Vec2(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)


@dataclass
class Vec3(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)
    z: float = betterproto.float_field(3)


@dataclass
class Vec4(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)
    z: float = betterproto.float_field(3)
    w: float = betterproto.float_field(4)


@dataclass
class Quaternion(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)
    z: float = betterproto.float_field(3)
    w: float = betterproto.float_field(4)


@dataclass
class Mat4x4f(betterproto.Message):
    values: List[float] = betterproto.float_field(1)


@dataclass
class Image(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)
    width: int = betterproto.int32_field(2)
    height: int = betterproto.int32_field(3)


@dataclass
class Header(betterproto.Message):
    frame_start_time: float = betterproto.float_field(1, group="_frame_start_time")
